### ISSUE TITLE
저점/고점의 레벨 산출 기준

### ISSUE THREAD

**Issue by luke-woojudaddy** [Jiho-Son/HLMarking#3]
ㅁ 저점, 고점을 정하는 기준은 과거와 미래 모두와 비교해서 정하되(현재 유지)
     저점, 고점의 레벨은 미래의 고점, 저점과 비교한 기준으로 산출 필요

ㅁ 이 때 저점, 고점에 따른 레벨의 비교 로직은 다음과 같다.
  - 저점의 레벨을 구할 때 : 레벨을 정하고자 하는 저점의 가격에서, 가장 가까운 미래의 고점에 얼마나 상승했는지
    ex) 레벨을 정하고자 하는 저점의 가격이 10이고, 가장 가까운 미래의 고점 가격이 15인 경우 : 50%
  - 고점의 레벨을 구할 때 : 레벨을 정하고자 하는 고점의 가격이, 가장 가까운 미래의 저점 대비 얼마나 높은지
    ex) 레벨을 정하고자 하는 고점의 가격이 10이고, 가장 가까운 미래의 저점 가격이 5인 경우 : 100%

ㅁ %별 레벨은 다음과 같다. (단위 : 퍼센트)
  - 1레벨 : 5 이상 10 미만
  - 2레벨 : 10 이상 20 미만
  - 3레벨 : 20 이상 50 미만
  - 4레벨 : 50 이상 100 미만
  - 5레벨 : 100 이상

**Comment by Jiho-Son** [comment]
got it
